platform :ios, '7.0'

pod 'AFNetworking', '3.0.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'FMDB', '~> 2.6'
pod 'UMengAnalytics-NO-IDFA'
pod 'SDWebImage', '~> 3.7.5'
pod 'libqrencode', '~> 3.4.2', :inhibit_warnings => true
#pod update --verbose --no-repo-update 